# Generated by Django 3.0.6 on 2020-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpatient',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200, null=True),
        ),
    ]
