# Generated by Django 3.0.6 on 2020-06-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_createpatient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpatient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='createpatient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='createpatient',
            name='height',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='createpatient',
            name='weight',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='createpatient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
    ]
